# ------------------------------------------------------------
# 🚀 GitHub Actions Workflow for ASP.NET Core + Azure Web App
# ------------------------------------------------------------
# This workflow:
# 1️⃣ Builds your ASP.NET Core Web API
# 2️⃣ Publishes it to Azure using your Publish Profile
# ------------------------------------------------------------

name: Build and deploy ASP.Net Core app to Azure Web App - BincomFourthAssignment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BincomFourthAssignment'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BINCOMFOURTHASSIGNMENT }}
          package: .
